apiVersion: apps/v1 
kind: Deployment
metadata:
  name: dev
  namespace: dev
  labels:
    app: will-playground 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: will-playground
  template:
    metadata:
      labels:
        app: will-playground
    spec:
      containers:
      - name: playground
        image: "wil42/playground:v1"
        ports:
        - containerPort: 8888
--- 

apiVersion: v1
kind: Service
metadata:
  name: will-playground-service
  namespace: dev
spec:
  selector:
    app: will-playground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer