apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: wil-playground-app
  namespace: argocd
spec:
  destination:
    name : ''
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app
    repoURL: https://github.com/lusehair/iot-p3 
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
    